#! /bin/bash
#$ -cwd
#$ -S /bin/bash
#$ -V
#$ -t 1-200
#$ -q all.q
#$ -pe mpi_smp 2
#$ -e /home/ubuntu/error
#$ -o /home/ubuntu/out
#source /etc/bash.bashrc
echo "Start - TASKID " $SGE_TASK_ID " : " $(date)
# Run anatomical spatial qap
roi=${SGE_TASK_ID}
time /abide_data/correlate_w.py ${roi} > /abide_data/correlation_logs/${SGE_TASK_ID}_w_correlation.log 2>&1
echo "End - TASKID " $SGE_TASK_ID " : " $(date)
